# Generated by Django 3.2.11 on 2022-04-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_leaderboard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.IntegerField(default='0'),
        ),
    ]
